### ISSUE TITLE
syntax error when try to encrypt the jquery.linkify.min.js using Obfuscator

### ISSUE THREAD

**Issue by ranaesam** [SoapBox/jQuery-linkify#54]
Hello, 
Can you please check the syntax errors when you try to encrypt the linkify file using obfuscator .

Thank you, 

Rana .

**Comment by nfrasser** [comment]
Couldn't reproduce this with the `.min.js` file, but I think this might be your problem:

If you're concatenating linkify to another JS file, make sure there's a line break at the end of the last line if the last line is a comment.

I got a syntax error when concatenating jquery.min.js and linkify.min.js because jquery.min.js ended with this line

```
//# sourceMappingURL=jquery.min.map
```

which effectively "commented out" the beginning of the `/*` comment in linkify.

So the solution here would be to either remove the source mapping comment or add a `\n` line break to the end.

**Comment by Polfo** [comment]
Great to see how authors of open source software go well beyond supporting their plugin. Thanks @nfrasser 
+1

**Comment by ranaesam** [comment]
Hello, 

i'm trying to encrypt the file using http://javascriptobfuscator.com/ and error appear on syntax line no 74
![error](https://cloud.githubusercontent.com/assets/8872183/5833126/1a4b5c9a-a158-11e4-9f0c-b3a41a03d905.JPG)

Thanks

**Comment by nfrasser** [comment]
The line that JavaScript obfuscator seems to be having trouble with is this one:

```js
            for (var option in options) "undefined" == typeof options[option] && delete options[option];
```

(Which is actually "prettified" output from [UglifyJs](https://github.com/mishoo/UglifyJS)). Nothing syntactically incorrect here, so it's likely a problem with javascriptobfuscator rather than Linkify.

Tried out this one http://www.jsobfuscate.com/index.php and it seems to do the trick. Hope that helps.

**Comment by nfrasser** [comment]
@Polfo :+1: !!

**Comment by ranaesam** [comment]
ok, thanks a lot
